spring:
    datasource:
        url: jdbc:mysql://10.171.161.180/steam?characterEncoding=utf8
        username: steam
        password: steam
    jpa:
        database: MYSQL
        show-sql: true
    #Hibernate ddl auto
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect